# Generated by Django 4.0.4 on 2022-06-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='empresa',
        ),
    ]
