# Generated by Django 4.0.4 on 2022-06-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioApp', '0002_remove_usuario_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='informacoesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(max_length=3)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=2)),
                ('telefone', models.CharField(max_length=16)),
                ('primeiroEmprego', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='nomeUsuario',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
