# Generated by Django 4.0.4 on 2022-06-26 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarioApp', '0003_informacoesusuario_usuario_nomeusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.AddField(
            model_name='informacoesusuario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
