# Generated by Django 4.0.4 on 2022-06-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarioApp', '0001_initial'),
        ('tagApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=models.CharField(max_length=100), max_length=255, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioApp.usuario')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagApp.tag')),
            ],
            options={
                'ordering': ('-criacao',),
            },
        ),
    ]
